apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-green
  labels:
    app: flask-app
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
      version: green
  template:
    metadata:
      labels:
        app: flask-app
        version: green
    spec:
      containers:
      - name: flask-app
        image: jay16nair/flask-blue-green:green
        ports:
        - containerPort: 5000
        env:
        - name: VERSION
          value: "green"
        - name: PORT
          value: "5000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
